# Generated by Django 4.2.3 on 2023-07-18 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driver_name', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('car_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.carnumber')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.contractor')),
                ('fraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.fraction')),
            ],
        ),
    ]
